services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=technique-data'
      - 'POSTGRES_PASSWORD=ContraseniaSegura34@'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
